### PR TITLE
Add preliminary symfony4 support

### PR DESCRIPTION
**Pull request by andig**
Not a complete solution according to https://github.com/php-pm/php-pm/issues/282

### CODE REVIEW

**Comment by dave-redfern** [comment]
I made a phar builder for ppm and added support for SF3/4 kernels through Kernel discovery (based on code in Laravel): https://github.com/dave-redfern/somnambulist-phppm-phar/blob/master/src/Bootstraps/AbstractSymfony.php. Feel free to adapt / borrow / ignore 😄

**Comment by andig** [comment]
@dave-redfern I'd be happy to have a PR. No symfony knowledge on my side :O

**Comment by dave-redfern** [comment]
@andig Done! https://github.com/php-pm/php-pm-httpkernel/pull/74 - hope it's OK. 😄

**Comment by marcj** [comment]
Conflicts, I will add it directly for the moment.

**Pull request closed without merging**
