### PR TITLE
Fix Composer validation error

### PR DESCRIPTION
**Pull request by andig**

### CODE REVIEW

**Comment by acasademont** [comment]
sorry @andig didn't see this! let me take a look

**Comment by acasademont** [comment]
I broke it on https://github.com/php-pm/php-pm-httpkernel/pull/144

But as the travis was failing back then I didn't see it 🤦‍♂️ Let's see how can we fix that

**Comment by andig** [comment]
Good you‘re back- I have very little time for php right now :O

**Comment by acasademont** [comment]
Yes, I wish I could give this project some deserved love. Funny thing that the quarantine keeps me busier at work than I expected!

**Comment by acasademont** [comment]
See #167

**Pull request closed without merging**
