### PR TITLE
Fix https://github.com/php-pm/php-pm-httpkernel/issues/33

### PR DESCRIPTION
**Pull request by andreasroman**
Added Bootstraps/Lumen-Class.
Fixes https://github.com/php-pm/php-pm-httpkernel/issues/33

Use:
./vendor/bin/ppm start --bootstrap=lumen

### CODE REVIEW

**Comment by andig** [comment]
Cannot test this but looks ok!

**Comment by marcj** [comment]
Is Lumen so different to Laravel?

**Comment by marcj** [comment]
I thought https://github.com/php-pm/php-pm-httpkernel/blob/master/Bootstraps/Laravel.php covers already Lumen.

**Comment by adamlc** [comment]
For whatever reason bootstrap/autoload.php doesn't exist in Lumen so it doesn't work :(

**Pull request closed without merging**
