### PR TITLE
Kentr add server vars

### PR DESCRIPTION
**Pull request by kentr**

### CODE REVIEW

**Comment by andig** [comment]
That might work. Where do you get $parameters from? Has this been tested?

**Comment by kentr** [comment]
I tested manually with some basic GET and POST requests for a Drupal app, and inspected via debugger.  If there are other required tests, I'll need some pointers on testing further.

The resulting values for `$syRequest->headers` and `$syRequest->server` are in [this comment](https://github.com/php-pm/php-pm-httpkernel/issues/14#issuecomment-175209950).

`$parameters` is set to either `$query` or `$post`, depending on `$method`.  

That's based on the assumption that `Request::create()` expects it like that and uses `$parameters` to populate `Request::$query` or `Request::$request` depending on `$method`.  

The code I'm looking at is `\Symfony\Component\HttpFoundation\create()`, ~ line 361:

```php
        switch (strtoupper($method)) {
            case 'POST':
            case 'PUT':
            case 'DELETE':
                if (!isset($server['CONTENT_TYPE'])) {
                    $server['CONTENT_TYPE'] = 'application/x-www-form-urlencoded';
                }
                // no break
            case 'PATCH':
                $request = $parameters;
                $query = array();
                break;
            default:
                $request = array();
                $query = $parameters;
                break;
        }
```

**Comment by kentr** [comment]
Based on the above code, it would probably be better to initialize `$parameters` with something like this:

`$parameters = in_array($method, ['POST', 'PUT', 'DELETE', 'PATCH']) ? $request : $query;`

Thoughts?

**Comment by marcj** [comment]
Well, $parameters  can now be querString params or parsed parameters from the request body? What if you have both? A POST with body and QueryString?

**Comment by kentr** [comment]
BTW, there's some background on this PR in #14.

> Well, $parameters can now be querString params or parsed parameters from the request body? What if you have both? A POST with body and QueryString?

Good question.

[`SymfonyRequest::create()`](https://github.com/symfony/http-foundation/blob/master/Request.php#L379) appears to extract the query string from the `$uri` parameter.  

In this PR, that mechanism is failing because `$uri` doesn't contain the query string.

Here's a [gist](https://gist.github.com/kentr/df78111c371194742898#file-httpkernel-php-L139) with a correction for the problem and some other pieces filled in.

**Expected Results**

[Here's](https://gist.github.com/kentr/dca6cf2f253fd2ded6b8) a baseline of an actual `Request` object while running under nginx / PHP-FPM.  The request was created with `Request::createFromGlobals()` (as part of the standard Drupal request flow).

**Actual Results**

[This](https://gist.github.com/kentr/5e5501c619ade0fdecfc) is the request object under PHP-PM resulting from the suggested `mapRequest()` code.

**Comment by marcj** [comment]
Beside the ServerBag this look pretty good to me!

**Comment by kentr** [comment]
@marcj: I moved the repo to a temporary organization [php-pm-drupal/php-pm-drupal](https://github.com/php-pm-drupal/php-pm-drupal) and granted you admin access to the repo.

Please transfer it to the php-pm organization when you like.

**Comment by andig** [comment]
> Beside the ServerBag this look pretty good to me!

I would say thats ok since the current version always initalizes server to be empty. +1 for merging from my side (though untested- it it breaks we roll it back).

**Comment by marcj** [comment]
Pushed today some changes that should now completely populate the Symfony Request with all its needed values ($post, $query, $files, $server, etc)
(see also https://github.com/php-pm/php-pm-httpkernel/issues/14#issuecomment-198150589)

Guess this is obsolete now. Feel free to ping me back if something is missing. :)

**Pull request closed without merging**
