### PR TITLE
Updated to Symfony 3

### PR DESCRIPTION
**Pull request by gnugat**
Added support for Symfony 3.

### CODE REVIEW

**Comment by hbroer** [comment]
Not shure, but i think Stack/builder needs Version dev-master

**Comment by marcj** [comment]
Not so important, I don't know anyone using stack builder, so we could basically remove it completely. It does also currently not even work because of a missing interface `StackableBootstrapInterface`, and since no one complained, it should be free to remove :)

**Comment by andig** [comment]
^2.6 should include 2.8? Then +1.

**Comment by gnugat** [comment]
@andig: yes it does, `^2.6|^3.0` is basically the same as `>=2.6,<4.0`.
@hbroer: yes, but we [can specify it in the project's `composer.json`](https://github.com/gnugat-examples/bench-sf-standard/blob/php-pm/composer.json#L34)
@marcj: I have no idea why PHP PM HttpKernel bridge requires `stack/builder` so it's your call ;)

**Comment by hbroer** [comment]
@gnugat yes, that is possible. But without that entry in projects composer.json composer install will fail.

@marcj i dont see real dependency on stack/builder. "Bootstraps/Laravel.php" contains a use statement without using it, and "Bridges/HttpKernel.php" only at one comment. Is it true, that it isn't required? 

https://github.com/php-pm/php-pm-httpkernel/search?utf8=%E2%9C%93&q=Builder

**Comment by gnugat** [comment]
@hbroer [It's been removed since your last comment](https://github.com/php-pm/php-pm-httpkernel/commit/4de2a1a8abcc71e87877b5ecf6aadebcf27e7025)

**Pull request merged**
