### PR TITLE
Fix https://github.com/php-pm/php-pm-httpkernel/issues/34

### PR DESCRIPTION
**Pull request by andig**
Fix https://github.com/php-pm/php-pm-httpkernel/issues/34

### CODE REVIEW

**Comment by andig** [comment]
Wait a moment, need to add the implements clause for Drupal as well.

**Comment by andig** [comment]
> Wait a moment, need to add the implements clause for Drupal as well.

Fixed. Should be good now.

**Comment by andig** [comment]
ping @marcj ok to go?

**Comment by marcj** [comment]
LGTM 👍

**Comment by andig** [comment]
Excellent, much appreciated.

**Pull request merged**
