### PR TITLE
fix broken tests

### PR DESCRIPTION
**Pull request by acasademont**
@andig this should fix your PR

### CODE REVIEW

**Comment by andig** [comment]
Travis is broken, too. No more status on PRs. But its erroring for different reason now: https://travis-ci.org/github/php-pm/php-pm-httpkernel

**Comment by andig** [comment]
Do you want to merge my pr, too, into yours?

**Comment by acasademont** [comment]
so on your PR there are 2 different commits, no? The Drupal bootstrap also usess the HttpKernel, that's why it's probably being required too

**Comment by andig** [comment]
I removed it as we‘re not testing it anywhere, but up to you

**Comment by acasademont** [comment]
@andig I put your composer commit in here, tests are green again

**Pull request merged**
