### PR TITLE
[#64]Update overdue and not sync with composer.json <-x-> composer.lock

### PR DESCRIPTION
**Pull request by drefixs**
- update composer.json minimum-stability from stable to dev
- update&sync composer.lock with composer.json

### CODE REVIEW

**Comment by andig** [comment]
From what I‘ve learned lock files for packages are disregarded by composer anyway and thus should not be committed. 

As for the stability- does this fix a particular issue you‘re seing? I don‘t think its required here.

**Comment by drefixs** [comment]
I just try to do minimal changes to do independently run php-pm like a tool for projects inside docker container.

When you try to do next:
`
mkdir ~/test
cd ~/test
composer create-project -s dev php-pm/php-pm
cd php-pm
composer require php-pm/httpkernel-adapter:dev-master
# and see the next problem http://prntscr.com/gt41b6
# try to change minimal stability to show the next problem
composer config minimum-stability dev
# run composer require again
composer require php-pm/httpkernel-adapter:dev-master
# and see other problem http://prntscr.com/gt43b6
`
In my case I temporary use php-pm/httpkernel-adapter like a tool and run php-pm from the 

/usr/local/share/httpkernel-adapter/vendor/php-pm/php-pm/bin/ppm start --cgi-path=/usr/local/bin/php --host=0.0.0.0 --port=8000 --app-env=dev --bootstrap=symfony --socket-pa
th=/tmp/ppm.socker --pidfile=/tmp/ppm.pid

But if we think about httpkernel-adapter like an independent component we need to stop require 
php-pm directly to fallow Dependency inversion. 

I see that you require php-pm to have the next interfaces
ApplicationEnvironmentAwareInterface
AsyncInterface
BootstrapInterface
BridgeInterface

But you don't need to require it directly from the php-pm, just move it to the abstraction layer(other repo only with interfaces) and require this repo in both packages.

**Comment by eugenekurasov** [comment]
About lock file you are right - when you do 'composer require' on other project he are disregarded.
@drefixs is do "git clone git@github.com:php-pm/php-pm-httpkernel.git && cd php-pm-httpkernel && **composer install**" and we should have in vendor php-pm/php-pm but didn't get php-pm after composer install..
Why him this is need? Maybe he don't want include this code to his project and use like proxy.

**Comment by andig** [comment]
Please install php-pm and then require php-pm-httpkernel. The other way round will not work.

**Comment by drefixs** [comment]
Is it not interesting to make php-pm to be independent from the application ?

I run php-pm installed independent from the application and it works now like php-fpm doesn't know anything about application, and to do it possible i require some change of the package deps now.

And now the one question that i have. Is php-pm project going to be independent from applications in the feature ?

**Comment by andig** [comment]
Should be fixed via https://github.com/php-pm/php-pm/pull/271

**Pull request closed without merging**
