### PR TITLE
[WIP] Watch changes on files that are resources within the container

### PR DESCRIPTION
**Pull request by fionera**
See issue: https://github.com/php-pm/php-pm-httpkernel/issues/147

### CODE REVIEW

**Comment by fionera** [comment]
The tests are failing because the Container is missing in the Mocks and PHPStan does not like the instanceof on a String

**Comment by acasademont** [comment]
I'd maybe wrap all that code in a `if ($this->debug)` condition?

you also have a special function `register_file` that you can use instead of calling the slaves directly

**Comment by fionera** [comment]
I still dont see the point why the reloading is blocked when debug is disabled.. But i added the two ideas :D

**Comment by dnna** [comment]
❤️ this PR (I was actually planning to do something similar because I keep needing this)
I'm guessing these tests have been broken for a while, might need a separate PR to fix them.

**Comment by andig** [comment]
Looks like the failure is unrelated but still new. I would appreciate an independent review of this pr (@dnna ?).

**Comment by dnna** [comment]
I submitted a PR that should fix the $container not found issue in the tests (#150), but @fionera I think the phpstan issue is related to this PR and should be fixed by you.

Other than that the PR looks fine and works well!

**Comment by andig** [comment]
Kicked of a rebuild

**Comment by dnna** [comment]
OK, now it breaks because it tries to access $container->containerDir in the new code. This should be fixable by simply adding a `$containerDir` property in `PHPPM\Tests\SymfonyMocks\Container` (not sure why phpunit became more strict all of a sudden with this, but its better). Since this now related with the PR I'm guessing this should be added here

**Comment by fionera** [comment]
@dnna the phpstan issue is already gone :) I add the $containerDir now...

**Pull request merged**
