### PR TITLE
Fix Webpack Encore Bundle EntrypointLookup reset

### PR DESCRIPTION
**Pull request by fionera**

### CODE REVIEW

**Comment by andig** [comment]
Could you take a look at the related and unrelated travis exceptions?

**Comment by fionera** [comment]
The exceptions happens because PHPStan is dumb. It trys to load the Class that I wrote as String...

**Comment by fionera** [comment]
Its a bug in PHPStan... https://github.com/phpstan/phpstan/issues/1871

**Comment by andig** [comment]
Yeah, thought so after looking at the function definition. You could add an exception for the time being.

**Comment by fionera** [comment]
Sorry for the ton of commits, when merging just make a Squash merge :)

**Comment by fionera** [comment]
A Exception in the .phpstan.neon will not help :/ PHPStan says this then... "Error message cannot be ignored, use excludes_analyse instead.". I would have to exclude the whole Bootstrap file from the checks.

**Comment by andig** [comment]
Waiting for bug in phpstan to be fixed then?

**Comment by fionera** [comment]
Currently yes since i didnt got the ignore to work

**Comment by acasademont** [comment]
The webpack bundle afaik should be able to reset itself as of version 1.7.2, correct? I believe this is not needed anymore and the resets can be removed?

**Comment by acasademont** [comment]
Relevant commit is here https://github.com/symfony/webpack-encore-bundle/commit/3a3eac35c83038f5dd08d584480e82f03aedcf7e

**Comment by fionera** [comment]
I didnt check it yet since I currently just patch this pr into my vendor folder. Will look if it works now without it.

**Comment by fionera** [comment]
I just tested it in my System and there it works :) So this isnt needed anymore ^^

**Pull request closed without merging**
